apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-global-$id
subjects:
- kind: User
  name: user-$id
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-reader-$id
  apiGroup: rbac.authorization.k8s.io

